# very special 32 bytes of stuff that encrypts your session I think?
tide_secret = "SHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHisthis32byet"

# your domain url
root_domain = "e-worm.club"

# what you want to call your server
server_name = "e-worm club"

# db_url must be prefixed with "sqlite:"
db_path = "sqlite:db/sqlite3.db"

# no home directory tildes please
file_directory = "/home/me/.flounder"

# where to find your custom css etc
static_path = "static"
